vlab-research/vlab

dashboard-frontend/src/types/study.ts
@nandanrao 
This PR it's the same as this one https://github.com/vlab-research/vlab/pull/9 that has been just merged.
I forgot to update the base branch to main, so when merged it was merged into a feature branch (5-setup-frontend-codebase-for-dashboard) 😢
=> (#8) Create initial types for Study data

README.md
- Adds some status badges to the readme for CI/CD jobs
- Adds Logo for brand recognition
=> docs: update readme with status and image

dashboard-api/go.mod, dashboard-api/go.sum, dashboard-api/internal/platform/server/handler/studyconf/create.go, dashboard-api/internal/platform/server/handler/studyconf/create_test.go, dashboard-api/internal/platform/server/handler/studyconf/read.go, dashboard-api/internal/platform/server/handler/studyconf/read_test.go, dashboard-api/internal/platform/server/server.go, dashboard-api/internal/platform/storage/studyconf_repository.go, dashboard-api/internal/platform/storage/studyconf_repository_test.go, dashboard-api/internal/testhelpers/testhelpers.go, dashboard-api/internal/types/studyconf.go, dashboard-api/internal/types/studyconf_test.go, devops/seed/seed_02.sql
- adds get study config endpoint
Fixes: https://github.com/vlab-research/vlab/issues/124
=> feat: add get study config endpoint

dashboard-api/internal/platform/server/handler/studyconf/create_test.go, dashboard-api/internal/platform/server/handler/studyconf/read_test.go, dashboard-api/internal/testhelpers/databasestudyconf.go, dashboard-api/internal/testhelpers/studyconfig.go, dashboard-api/internal/types/studyconf.go, dashboard-api/internal/types/studyconf_test.go, devops/seeds/20230322121948_studyconf.up.sql
- adds recruitment to the study conf setup
=> chore: add recruitment conf to study conf

dashboard-api/go.mod, dashboard-api/go.sum, dashboard-api/internal/platform/server/handler/studyconf/create_test.go, dashboard-api/internal/platform/server/handler/studyconf/read_test.go, dashboard-api/internal/testhelpers/databasestudyconf.go, dashboard-api/internal/testhelpers/studyconfig.go, dashboard-api/internal/types/studyconf.go, dashboard-api/internal/types/studyconf_test.go, devops/seeds/20230322121948_studyconf.up.sql
- adds destination to study conf api for dashboard
=> feat: add destinations to study conf

dashboard-api/internal/platform/storage/studyconf_repository.go, dashboard-api/internal/platform/storage/studyconf_repository_test.go
- we where always fetching the oldest study confs and not the neweset, this fixes that issue
=> fix: ordering of returned study conf

dashboard-api/internal/platform/server/handler/studyconf/create_test.go, dashboard-api/internal/platform/server/handler/studyconf/read_test.go, dashboard-api/internal/testhelpers/databasestudyconf.go, dashboard-api/internal/testhelpers/studyconfig.go, dashboard-api/internal/types/studyconf.go, dashboard-api/internal/types/studyconf_test.go
- adds creative conf to the study conf setup to allow the API to start setting it
=> feat: add creatives to study conf

dashboard-frontend/src/App.tsx
The route path was showing a blank screen on page load – this fixes that by taking the user directly to /studies
=> chore: fixes routepath routing

README.md
- updates readme to give the project layout
- links to our hosted documentation for how to use our platform
=> chore: update readme 

dashboard-frontend/src/server.ts
- fixes mirage
- adds study conf to mirage
=> chore: adds study conf to mirage

dashboard-api/internal/server/handler/accounts/create.go, dashboard-api/internal/server/handler/accounts/delete.go, dashboard-api/internal/server/handler/accounts/delete_test.go, dashboard-api/internal/server/handler/facebook/token.go, dashboard-api/internal/server/server.go, dashboard-api/internal/storage/account.go, dashboard-api/internal/testhelpers/testhelpers.go, dashboard-api/internal/types/account.go
- add delete endpoint for accounts
=> feat: add endpoint to delete account

dashboard-frontend/package-lock.json, dashboard-frontend/package.json
- fix mirage server process error
=> fix: hotfix mirage server

dashboard-frontend/package.json, dashboard-frontend/src/helpers/arrays.spec.ts, dashboard-frontend/src/helpers/arrays.ts, dashboard-frontend/src/hooks/useAuthenticatedApi.tsx, dashboard-frontend/src/pages/AccountsPage/AccountsPage.tsx, dashboard-frontend/src/pages/AccountsPage/InputAccountCredentials.tsx, dashboard-frontend/src/pages/StudiesPage/StudyList.tsx, dashboard-frontend/src/server.ts, dashboard-frontend/src/types/account.ts
=> chore: run prettier on all files

dashboard-frontend/src/components/DeleteButton.tsx, dashboard-frontend/src/components/LoadingSpinner.tsx, dashboard-frontend/src/components/PrimaryButton.tsx, dashboard-frontend/src/helpers/api.ts, dashboard-frontend/src/pages/AccountsPage/AccountList.tsx, dashboard-frontend/src/pages/AccountsPage/useAccounts.tsx, dashboard-frontend/src/pages/AccountsPage/useDeleteAccount.tsx
- adds ability to delete accounts from dashboard
=> chore: add ability to delete account

README.md, dashboard/netlify.toml
- fixes netlify build directory
- fixes logo link on readme
=> fix: netlify build directory

api/Dockerfile
=> fix: api docker build

api/.env-example, api/internal/server/handler/facebook/token.go, api/internal/server/handler/facebook/token_test.go, dashboard/.env-example, dashboard/.gitignore, dashboard/Makefile, dashboard/README.md, dashboard/craco.config.js, dashboard/package-lock.json, dashboard/src/components/InfoBanner.tsx, dashboard/src/helpers/api.ts, dashboard/src/pages/AccountsPage/AccountCreateModal.tsx, dashboard/src/pages/AccountsPage/AccountList.tsx, dashboard/src/pages/AccountsPage/AccountsPage.tsx, dashboard/src/pages/AccountsPage/InputAccountCredentials.tsx, dashboard/src/pages/AccountsPage/generateFacebookAccount.tsx, dashboard/src/types/account.ts
- adds facebook connection as a connected account
- There are some facebook specific formatting we need for accounts (for instance not showing the credentials to the user and showing the banner with the beta information)
- Happy on some feedback on the implementation and how to make more readable
- This will require us adding some environment variables to the forntend and backend, we will start with the test app and once the main app is approved use that one
- This also adds TLS to the local environment, you will have to update your local dev environment for the frontend, please read the updated README for more information
Facebook connected account
New connected account modal
=> chore: adds facebook as a connected account

dashboard/src/pages/AccountsPage/AccountCreateModal.tsx, dashboard/src/pages/AccountsPage/InputAccountCredentials.tsx
- fixes spelling mistake on banner
=> chore: fix spelling on banner

dashboard/src/pages/AccountsPage/InputAccountCredentials.tsx
- fix accounts where not using react state to handle changes
=> fix: accounts using state instead of intial state

dashboard/src/App.tsx, dashboard/src/fixtures/recruitment/types.ts, dashboard/src/pages/StudyConfPage/StudyConfPage.tsx, dashboard/src/pages/StudyConfPage/components/Form.tsx, dashboard/src/pages/StudyConfPage/forms/General.tsx, dashboard/src/pages/StudyConfPage/forms/recruitment/Destination.tsx, dashboard/src/pages/StudyConfPage/forms/recruitment/PipelineExperiment.tsx, dashboard/src/pages/StudyConfPage/forms/recruitment/Recruitment.tsx, dashboard/src/pages/StudyConfPage/forms/recruitment/Simple.tsx
- implemented the recruitment form with dynamic form rendering for each of the recruitment types 
- the user can input, save and edit recruitment data
=> feature: recruitment conf

api/internal/server/handler/studyconf/create.go, api/internal/server/handler/studyconf/create_test.go, api/internal/testhelpers/testhelpers.go
- fixes bug where study conf is not validated
=> fix: studyvonf was skipping validation on create

dashboard/src/pages/StudyConfPage/StudyConfPage.tsx, dashboard/src/pages/StudyConfPage/forms/creatives/Creative.tsx, dashboard/src/pages/StudyConfPage/forms/creatives/Creatives.tsx, dashboard/src/types/conf.ts
- implemented the creatives form 
- user can input, add, save, edit and delete creatives
=> feature: creatives conf

api/internal/server/handler/accounts/list.go, api/internal/server/handler/accounts/list_test.go, api/internal/storage/account.go, api/internal/types/account.go
- adds a filter to the account list
=> chore: add filter to account

dashboard/src/helpers/api.ts, dashboard/src/pages/StudyConfPage/forms/strata/Strata.tsx, dashboard/src/pages/StudyConfPage/forms/strata/useAccounts.tsx
- adds fetching of facebook credentials from the backend on the load of the strata form
=> feat: adds the fetching of facebook credentials to the strata page

dashboard/src/pages/StudyConfPage/forms/creatives/Creative.tsx, dashboard/src/pages/StudyConfPage/forms/creatives/Creatives.tsx, dashboard/src/pages/StudyConfPage/forms/destinations/Destinations.tsx, dashboard/src/pages/StudyConfPage/forms/general/General.tsx, dashboard/src/pages/StudyConfPage/forms/recruitment/Destination.tsx, dashboard/src/pages/StudyConfPage/forms/recruitment/Recruitment.tsx, dashboard/src/types/conf.ts
Updated the UI to allow for optional conf fields e.g instagram ID
=> chore: allow for optional conf fields
